parameters:
    app.name: WebSystem
    app.subname: framework
    app.version: 0.1.0
    app.author: DevMediaLab
    debug: true

services:
    framework:
        class: DevMediaLab\Framework
        arguments:
            - @dispatcher
            - @controller_resolver
            - @service_container

    dispatcher:
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments:
            - @service_container

    controller_resolver:
        class: Symfony\Component\HttpKernel\Controller\ControllerResolver
        arguments:
            - @?logger

    router_builder:
        class: DevMediaLab\RouterBuilder
        arguments:
            - @routes

    routes:
        class: Symfony\Component\Routing\RouteCollection

    url_matcher:
        class: Symfony\Component\Routing\Matcher\UrlMatcher
        arguments:
            - @routes
            - @request_context

    stage_controller:
        class: StageController
        arguments:
            - @service_container

    request_context:
        class: Symfony\Component\Routing\RequestContext

    exception_controller:
        class: DevMediaLab\ErrorInterceptor
        arguments:
            - @exception_handler

    exception_handler:
        class: Symfony\Component\HttpKernel\Debug\ExceptionHandler
        arguments:
            - %debug%

    # Listeners

    listener.router:
        class: Symfony\Component\HttpKernel\EventListener\RouterListener
        arguments:
            - @url_matcher
            - @request_context
            - @?logger
        tags:
            - { name: kernel.event_subscriber }

    listener.response:
        class: Symfony\Component\HttpKernel\EventListener\ResponseListener
        arguments:
            - UTF-8
        tags:
            - { name: kernel.event_subscriber }

    listener.exception:
        class: Symfony\Component\HttpKernel\EventListener\ExceptionListener
        arguments:
            - [@exception_controller, 'handle']
            - @?logger
        tags:
            - { name: kernel.event_subscriber }

    listener.request_parameter:
        class: DevMediaLab\EventListener\RequestParameterListener
        tags:
            - { name: kernel.event_subscriber }

    listener.string_response:
        class: DevMediaLab\EventListener\StringResponseListener
        tags:
            - { name: kernel.event_subscriber }
